name: widget
version: 0.2.0
author: Kevin Moore <kevin@thinkpixellab.com>
description: A set of reusable Web Components for Dart applications
homepage: https://github.com/kevmoo/widget.dart
environment:
  sdk: '>=0.3.7+6.r18717'
dependencies:
  unittest: '>=0.3.7+6'
  html5lib: '>=0.3.3'
  bot: '>=0.14.0'
  web_ui: '>=0.3.3+1'
  meta: '>=0.3.7+6'
