name:  widget
homepage: https://github.com/kevmoo/widget.dart
description:  A set of reusable Web Components for Dart applications
version: 0.0.1
dependencies:
  unittest: '>=0.2.9 <2.10.0'
  web_ui: '>=0.2.11 <0.2.12'
  bot: 0.10.0
