name: widget
version: 0.2.5
author: Kevin Moore <kevin@thinkpixellab.com>
description: A set of reusable Web Components for Dart applications
homepage: https://github.com/kevmoo/widget.dart
environment:
  sdk: '>=0.4.5+1.r21094'
dependencies:
  html5lib: '>=0.4.1'
  bot: '>=0.16.3+1'
  web_ui: '>=0.4.5'
  meta: '>=0.4.5+1'
dev_dependencies:
  unittest: '>=0.4.5+1'
