name: widget
version: 0.2.5
author: Kevin Moore <kevin@thinkpixellab.com>
description: A set of reusable Web Components for Dart applications
homepage: https://github.com/kevmoo/widget.dart
environment:
  sdk: '>=0.4.7+1'
dependencies:
  html5lib: '>=0.4.3'
  bot: '>=0.20.0'
  bot_web: '>=0.20.0'
  web_ui: '>=0.4.6+1'
  meta: '>=0.4.7+1'
dev_dependencies:
  unittest: '>=0.4.7+1'
  hop: '>=0.21.0'
