name: widget
version: 0.3.0-dev
author: Kevin Moore <kevin@thinkpixellab.com>
description: A set of reusable Web Components for Dart applications
homepage: https://github.com/dart-lang/widget.dart
environment:
  sdk: '>=0.8.10+4'
dependencies:
  bot: '>=0.24.0'
  bot_web: '>=0.20.6'
  polymer: '>=0.8.10+4'
dev_dependencies:
  bot_test: '>=0.1.3'
  hop: '>=0.27.0'
  html5lib: '>=0.8.10+4'
  unittest: '>=0.8.10+4'
