name: widget
version: 0.2.0-dev
author: Kevin Moore <kevin@thinkpixellab.com>
description: A set of reusable Web Components for Dart applications
homepage: https://github.com/kevmoo/widget.dart
dependencies:
  unittest: '>=0.3.2'
  html5lib: '>=0.3.1'
  bot: '>=0.11.4'
  web_ui: '>=0.3.1'
