name: widget
version: 0.2.6-beta
author: Kevin Moore <kevin@thinkpixellab.com>
description: A set of reusable Web Components for Dart applications
homepage: https://github.com/kevmoo/widget.dart
environment:
  sdk: '>=0.5.7'
dependencies:
  bot: '>=0.20.1'
  bot_web: '>=0.20.1'
  html5lib: '>=0.4.3'
  meta: '>=0.4.7+1'
  web_ui: '>=0.4.7+3'
dev_dependencies:
  hop: '>=0.22.1+1'
  unittest: '>=0.4.7+1'
