name: widget
version: 0.3.0-dev
author: Kevin Moore <kevin@thinkpixellab.com>
description: A set of reusable Web Components for Dart applications
homepage: https://github.com/dart-lang/widget.dart
environment:
  sdk: '>=0.6.9'
dependencies:
  bot: '>=0.23.0'
  bot_web: '>=0.20.4'
  meta: '>=0.6.9'
  polymer:
    git:
      ref: polymer
      url: https://github.com/kevmoo/web-ui.git
    version: '>=0.4.15'
dev_dependencies:
  bot_test: '>=0.1.1'
  hop: '>=0.24.1'
  html5lib: '>=0.4.4'
  unittest: '>=0.6.9'
